### ISSUE TITLE
使用过程的一些问题

### ISSUE THREAD

**Issue by lovelyJason** [tangxiangmin/mock-server#1]
你好，大佬。下了你的工具，挺好用，但是有个问题。我引官方的mock.js文件时，使用他的Mock.mock(url,method,function(options){})方法的时候，发ajax请求的时候，options的body属性是能接收到我传的请求体的数据。开启了你的服务器后，在_mock.js文件里使用Mock.mock(url,method,function(options){})方法的时候，options为什么是这个
`{ type: 'function',
  template: [Function],
  name: '',
  parsedName: '',
  rule: {},
  context:
   { path: [ 2 ],
     templatePath: [ 2 ],
     currentContext: undefined,
     templateCurrentContext: [Function],
     root: undefined,
     templateRoot: [Function] } }`这个没用啊，拿不到参数啊
![Snipaste_2019-07-20_21-56-08](https://user-images.githubusercontent.com/50656459/61579563-38722100-ab39-11e9-818a-48f74a98044e.png)

**Comment by tangxiangmin** [comment]
> 你好，大佬。下了你的工具，挺好用，但是有个问题。我引官方的mock.js文件时，使用他的Mock.mock(url,method,function(options){})方法的时候，发ajax请求的时候，options的body属性是能接收到我传的请求体的数据。开启了你的服务器后，在_mock.js文件里使用Mock.mock(url,method,function(options){})方法的时候，options为什么是这个
> `{ type: 'function', template: [Function], name: '', parsedName: '', rule: {}, context: { path: [ 2 ], templatePath: [ 2 ], currentContext: undefined, templateCurrentContext: [Function], root: undefined, templateRoot: [Function] } }`这个没用啊，拿不到参数啊
> ![Snipaste_2019-07-20_21-56-08](https://user-images.githubusercontent.com/50656459/61579563-38722100-ab39-11e9-818a-48f74a98044e.png)

**Comment by tangxiangmin** [comment]
这个是之前版本的一个bug，本身没有支持mock模板传回调函数的形式。在最新的版本中，已经支持这种形式了，在回调函数中，会将koa请求上下文ctx传进来，然后就可以通过ctx.query、ctx.body的方式获取到请求参数了，你可以看一下代码仓库的readme。

另外，我好像忘记更新npm上的包了...等会我推一下，重新升级一下应该就可以了
